project:
  type: website
  output-dir: docs

website:
  title: "STA 9750 Fall 2024 - Jason Amey"
  description:
    Course Projects for STA 9750 at Baruch College - Jason Amey
  site-url: "https://jasonamey.github.io/STA9750-2024-FALL/"
  navbar:
    background: secondary
    search: false
 
 
include-in-header:
  - text: |
     <link rel = "shortcut icon" href = "images/favicon.ico" />
      <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">

  
format:
  html:
    theme: cosmo
    toc: true
    css: styles.css 
    include-in-header: |
      <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">


  