<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>mini01 – STA 9750 Fall 2024 - Jason Amey</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">STA 9750 Fall 2024 - Jason Amey</span>
    </a>
  </div>
        <div class="quarto-navbar-tools tools-end">
</div>
          <div id="quarto-search" class="" title="Search"></div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">




<section id="jason-amey-mini-project-01" class="level1">
<h1>Jason Amey Mini Project 01</h1>
<section id="fiscal-characteristics-of-major-us-public-transit-systems" class="level2">
<h2 class="anchored" data-anchor-id="fiscal-characteristics-of-major-us-public-transit-systems">Fiscal Characteristics of Major US Public Transit Systems</h2>
<p>Public transit in the United States serves a critical role in urban mobility. US transit serves millions of commuters while reducing congestion, pollution, and reliance on personal vehicles.</p>
<p>The fiscal efficiency of these systems varies widely. However understanding these financial dimensions is essential for evaluating the sustainability and performance of transit services in a variety of cities and regions.</p>
<p>This report explores data from major U.S. public transit systems, with analyis focused on factors such as: fare revenue per mile, vehicle revenue miles (VRM), unlinked passenger trips (UPT), and the ratio of expenses to farebox recovery.</p>
<p>This data provide insights into which systems operate most efficiently, which modes of transport generate the most revenue, and how these metrics differ across various regions in the United States.</p>
<p>Using tools from the R programming language, we explore these trends over time and the influence of population density, geography, and mode type on financial outcomes. Through this exploration, we hope to better understand the complex relationship between transit usage, financial sustainability, and regional transit characteristics.</p>
<section id="data-creation" class="level3">
<h3 class="anchored" data-anchor-id="data-creation">Data Creation :</h3>
<pre><code>if(!require("tidyverse")) install.packages("tidyverse")
library(tidyverse)

if(!require("DT")) install.packages("DT")
library(DT)

if(!require("stringr")) install.packages("stringr")
library(stringr)

if(!require("lubridate")) install.packages("lubridate")
library(lubridate)

FARES &lt;- readxl::read_xlsx("data/mp-01/2022_fare_revenue.xlsx") |&gt;
  select(-`State/Parent NTD ID`,
         -`Reporter Type`,
         -`Reporting Module`,
         -`TOS`,
         -`Passenger Paid Fares`,
         -`Organization Paid Fares`) |&gt;
  filter(`Expense Type` == "Funds Earned During Period") |&gt;
  select(-`Expense Type`)

EXPENSES &lt;- readr::read_csv("data/mp-01/2022_expenses.csv") |&gt;
  select(`NTD ID`,
         `Agency`,
         `Total`,
         `Mode`) |&gt;
  mutate(`NTD ID` = as.integer(`NTD ID`)) |&gt;
  rename(Expenses = Total) |&gt;
  group_by(`NTD ID`, `Mode`) |&gt;
  summarize(Expenses = sum(Expenses)) |&gt;
  ungroup()

TRIPS &lt;- readxl::read_xlsx("data/mp-01/2022_ridership.xlsx", sheet="UPT") |&gt;
  filter(`Mode/Type of Service Status` == "Active") |&gt;
  select(-`Legacy NTD ID`,
         -`Reporter Type`,
         -`Mode/Type of Service Status`,
         -`UACE CD`,
         -`TOS`) |&gt;
  pivot_longer(-c(`NTD ID`:`3 Mode`),
               names_to="month",
               values_to="UPT") |&gt;
  drop_na() |&gt;
  mutate(month=my(month)) # Parse _m_onth _y_ear date specs

MILES &lt;- readxl::read_xlsx("data/mp-01/2022_ridership.xlsx", sheet="VRM") |&gt;
  filter(`Mode/Type of Service Status` == "Active") |&gt;
  select(-`Legacy NTD ID`,
         -`Reporter Type`,
         -`Mode/Type of Service Status`,
         -`UACE CD`,
         -`TOS`) |&gt;
  pivot_longer(-c(`NTD ID`:`3 Mode`),
               names_to="month",
               values_to="VRM") |&gt;
  drop_na() |&gt;
  group_by(`NTD ID`, `Agency`, `UZA Name`,
           `Mode`, `3 Mode`, month) |&gt;
  summarize(VRM = sum(VRM)) |&gt;
  ungroup() |&gt;
  mutate(month=my(month)) # Parse _m_onth _y_ear date specs

USAGE &lt;- inner_join(TRIPS, MILES) |&gt;
  mutate(`NTD ID` = as.integer(`NTD ID`))

FINANCIALS &lt;- inner_join(FARES, EXPENSES, join_by(`NTD ID`, `Mode`))

FINANCIALS &lt;- FINANCIALS |&gt;
  rename(
         "mode" = "Mode"
  )

FINANCIALS &lt;- FINANCIALS |&gt;
  mutate(mode=case_when(
    mode == "HR" ~ "Heavy Rail",
    mode == "DR" ~ "Demand Response",
    mode == "FB" ~ "Ferry Boat",
    mode == "MB" ~ "Motor Bus",
    mode == "SR" ~ "Streetcar",
    mode == "TB" ~ "Trolleybus",
    mode == "VP" ~ "Vanpool",
    mode == "CB" ~ "Commuter Bus",
    mode == "RB" ~ "Bus Rapid Transit",
    mode == "LR" ~ "Light Rail",
    mode == "YR" ~ "Hybrid Rail",
    mode == "MG" ~ "Guided Transit (Monorail)",
    mode == "CR" ~ "Commuter Rail",
    mode == "AR" ~ "Alaska Railroad",
    mode == "TR" ~ "Tramway",
    mode == "HR" ~ "Heavy Rail",
    mode == "IP" ~ "Inclined Plane",
    mode == "PB" ~ "Publico",
    mode == "CC" ~ "Cable Car",
    TRUE ~ "Unknown"))</code></pre>
</section>
</section>
</section>
<section id="task-1---creating-syntactic-names" class="level1">
<h1>TASK 1 - Creating Syntactic Names</h1>
<p>Renaming column UZA Name to metro_area:</p>
<pre><code>USAGE &lt;- USAGE |&gt;
  rename("metro_area" = "UZA Name",
         "unlinked_passenge_trips" = "UPT",
         "vehicle_revenue_miles" = "VRM",
         "agency" = "Agency",
         "mode" = "Mode"
        ) |&gt;
  select(-"3 Mode")</code></pre>
<section id="output" class="level3">
<h3 class="anchored" data-anchor-id="output">output:</h3>
<table class="table-striped table-hover caption-top table">
<caption>Data for King County Transit</caption>
<colgroup>
<col style="width: 7%">
<col style="width: 11%">
<col style="width: 19%">
<col style="width: 5%">
<col style="width: 11%">
<col style="width: 23%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th>NTD ID</th>
<th>agency</th>
<th>metro_area</th>
<th>mode</th>
<th>month</th>
<th>unlinked_passenger_trips</th>
<th>vehicle_revenue_miles</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>King County</td>
<td>Seattle–Tacoma, WA</td>
<td>DR</td>
<td>2002-01-01</td>
<td>135,144</td>
<td>746,158</td>
</tr>
<tr class="even">
<td>1</td>
<td>King County</td>
<td>Seattle–Tacoma, WA</td>
<td>DR</td>
<td>2002-02-01</td>
<td>127,378</td>
<td>656,324</td>
</tr>
<tr class="odd">
<td>1</td>
<td>King County</td>
<td>Seattle–Tacoma, WA</td>
<td>DR</td>
<td>2002-03-01</td>
<td>136,030</td>
<td>726,578</td>
</tr>
<tr class="even">
<td>1</td>
<td>King County</td>
<td>Seattle–Tacoma, WA</td>
<td>DR</td>
<td>2002-04-01</td>
<td>142,204</td>
<td>736,975</td>
</tr>
<tr class="odd">
<td>1</td>
<td>King County</td>
<td>Seattle–Tacoma, WA</td>
<td>DR</td>
<td>2002-05-01</td>
<td>144,697</td>
<td>746,158</td>
</tr>
<tr class="even">
<td>1</td>
<td>King County</td>
<td>Seattle–Tacoma, WA</td>
<td>DR</td>
<td>2002-06-01</td>
<td>131,833</td>
<td>696,633</td>
</tr>
</tbody>
</table>
<hr>
</section>
</section>
<section id="task-2---recoding-the-mode-column" class="level1">
<h1>TASK 2 - Recoding the Mode Column</h1>
<p>Expanding DOT mode codes into their full definitions All of the code definitions are found here: <a href="https://www.transit.dot.gov/ntd/national-transit-database-ntd-glossary">National Transit Database NTD Glossary</a></p>
<pre><code>USAGE &lt;- USAGE |&gt;
  mutate(mode=case_when(
    mode == "HR" ~ "Heavy Rail",
    mode == "DR" ~ "Demand Response",
    mode == "FB" ~ "Ferry Boat",
    mode == "MB" ~ "Motor Bus",
    mode == "SR" ~ "Streetcar",
    mode == "TB" ~ "Trolleybus",
    mode == "VP" ~ "Vanpool",
    mode == "CB" ~ "Commuter Bus",
    mode == "RB" ~ "Bus Rapid Transit",
    mode == "LR" ~ "Light Rail",
    mode == "YR" ~ "Hybrid Rail",
    mode == "MG" ~ "Guided Transit (Monorail)",
    mode == "CR" ~ "Commuter Rail",
    mode == "AR" ~ "Alaska Railroad",
    mode == "TR" ~ "Tramway",
    mode == "IP" ~ "Inclined Plane",
    mode == "PB" ~ "Publico",
    mode == "CC" ~ "Cable Car",
    TRUE ~ "Unknown"))

sample_n(USAGE, 20) |&gt;
  select(agency, metro_area, mode)</code></pre>
<section id="output-1" class="level3">
<h3 class="anchored" data-anchor-id="output-1">output:</h3>
<table class="table-striped table-hover caption-top table">
<caption>Data for Full Definition Transit Modes</caption>
<colgroup>
<col style="width: 49%">
<col style="width: 32%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th>agency</th>
<th>metro_area</th>
<th>mode</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Birmingham-Jefferson County Transit Authority</td>
<td>Birmingham, AL</td>
<td>Motor Bus</td>
</tr>
<tr class="even">
<td>Yolo County Transportation District</td>
<td>Sacramento, CA</td>
<td>Motor Bus</td>
</tr>
<tr class="odd">
<td>Michiana Area Council of Governments</td>
<td>Elkhart, IN–MI</td>
<td>Motor Bus</td>
</tr>
<tr class="even">
<td>Lower Rio Grande Valley Development Council</td>
<td>McAllen, TX</td>
<td>Demand Response</td>
</tr>
<tr class="odd">
<td>Potomac and Rappahannock Transportation Commission</td>
<td>Washington–Arlington, DC–VA–MD</td>
<td>Demand Response</td>
</tr>
<tr class="even">
<td>Greater Richmond Transit Company</td>
<td>Richmond, VA</td>
<td>Vanpool</td>
</tr>
<tr class="odd">
<td>Stanislaus Regional Transit Authority</td>
<td>Modesto, CA</td>
<td>Demand Response</td>
</tr>
<tr class="even">
<td>Worcester Regional Transit Authority</td>
<td>Worcester, MA–CT</td>
<td>Demand Response</td>
</tr>
<tr class="odd">
<td>Chattanooga Area Regional Transportation Authority</td>
<td>Chattanooga, TN–GA</td>
<td>Motor Bus</td>
</tr>
<tr class="even">
<td>Knoxville-Knox County Community Action Committee</td>
<td>Knoxville, TN</td>
<td>Demand Response</td>
</tr>
<tr class="odd">
<td>Pinellas Suncoast Transit Authority</td>
<td>Tampa–St.&nbsp;Petersburg, FL</td>
<td>Bus Rapid Transit</td>
</tr>
<tr class="even">
<td>Laketran</td>
<td>Cleveland, OH</td>
<td>Commuter Bus</td>
</tr>
<tr class="odd">
<td>METRO Regional Transit Authority</td>
<td>Akron, OH</td>
<td>Motor Bus</td>
</tr>
<tr class="even">
<td>Regional Transportation Commission of Washoe County</td>
<td>Reno, NV–CA</td>
<td>Demand Response</td>
</tr>
<tr class="odd">
<td>Kanawha Valley Regional Transportation Authority</td>
<td>Charleston, WV</td>
<td>Motor Bus</td>
</tr>
<tr class="even">
<td>Maryland Transit Administration</td>
<td>Baltimore, MD</td>
<td>Light Rail</td>
</tr>
<tr class="odd">
<td>Transit Joint Powers Authority for Merced County</td>
<td>Merced, CA</td>
<td>Demand Response</td>
</tr>
<tr class="even">
<td>Broward County Board of County Commissioners</td>
<td>Miami–Fort Lauderdale, FL</td>
<td>Motor Bus</td>
</tr>
<tr class="odd">
<td>Regional Transportation Program, Inc.</td>
<td>Portland, ME</td>
<td>Demand Response</td>
</tr>
<tr class="even">
<td>Central Midlands Regional Transportation Authority</td>
<td>Columbia, SC</td>
<td>Commuter Bus</td>
</tr>
</tbody>
</table>
<hr>
</section>
</section>
<section id="task-3---answering-instructor-specified-questions-with-dplyr" class="level1">
<h1>TASK 3 - Answering Instructor Specified Questions with dplyr</h1>
<p>Using functions we have studied in class, including filter, group_by, summarize, arrange, answer the following questions in your analysis:</p>
<section id="question-1" class="level3">
<h3 class="anchored" data-anchor-id="question-1">Question 1</h3>
<p>What transit agency had the most total VRM in this sample?</p>
<pre><code>USAGE |&gt;
  filter(!is.na(agency)) |&gt;
  group_by(agency) |&gt;
  summarize(total = sum(vehicle_revenue_miles)) |&gt;
  arrange(desc(total))</code></pre>
</section>
<section id="output-2" class="level3">
<h3 class="anchored" data-anchor-id="output-2">output:</h3>
<table class="table-striped table-hover caption-top table">
<caption>Data for Agency with Largest Vehicle Revenue Miles</caption>
<colgroup>
<col style="width: 84%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th>agency</th>
<th>total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>MTA New York City Transit</td>
<td>10,832,855,350</td>
</tr>
<tr class="even">
<td>New Jersey Transit Corporation</td>
<td>5,645,525,525</td>
</tr>
<tr class="odd">
<td>Los Angeles County Metropolitan Transportation Authority</td>
<td>4,354,016,659</td>
</tr>
<tr class="even">
<td>Washington Metropolitan Area Transit Authority</td>
<td>2,821,950,701</td>
</tr>
<tr class="odd">
<td>Chicago Transit Authority</td>
<td>2,806,202,144</td>
</tr>
</tbody>
</table>
</section>
<section id="answer-1" class="level3">
<h3 class="anchored" data-anchor-id="answer-1">Answer 1</h3>
<p>MTA New York City Transit: <strong>10,832,855,350 Vehicle Revenue Miles</strong></p>
<p><strong>Note:</strong></p>
<p>New York City is the largest city in the United States and the “big city” with the highest percentage of its residents using mass transit. These findings are in line with the signature characteristics of NYC’s transportation demographics.</p>
<hr>
</section>
<section id="question-2" class="level3">
<h3 class="anchored" data-anchor-id="question-2">Question 2:</h3>
<p>What transit mode had the most total VRM in this sample?</p>
<pre><code>USAGE |&gt;
  filter(!is.na(mode)) |&gt;
  group_by(mode) |&gt;
  summarize(total_vrm = sum(vehicle_revenue_miles, na.rm = TRUE)) |&gt;
  arrange(desc(total_vrm))</code></pre>
</section>
<section id="output-3" class="level3">
<h3 class="anchored" data-anchor-id="output-3">output:</h3>
<table class="table-striped table-hover caption-top table">
<caption>Data for Mode with Largest Vehicle Revenue Miles</caption>
<thead>
<tr class="header">
<th>mode</th>
<th>total_vrm</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Motor Bus</td>
<td>49,444,494,088</td>
</tr>
<tr class="even">
<td>Demand Response</td>
<td>17,955,073,508</td>
</tr>
<tr class="odd">
<td>Heavy Rail</td>
<td>14,620,362,107</td>
</tr>
<tr class="even">
<td>Commuter Rail</td>
<td>6,970,644,241</td>
</tr>
<tr class="odd">
<td>Vanpool</td>
<td>3,015,783,362</td>
</tr>
</tbody>
</table>
</section>
<section id="answer-2" class="level3">
<h3 class="anchored" data-anchor-id="answer-2">Answer 2</h3>
<p>Motor Bus: <strong>49,444,494,088 Vehicle Revenue Miles</strong></p>
<p><strong>Note:</strong></p>
<p>Outside a few major eastern US cities, much of the United States transportation infrastructure is meant to serve motorized vehicles. It is logical then that the motor bus would far outnumber the miles traveled by rail and other forms of transit.</p>
<hr>
</section>
<section id="question-3" class="level3">
<h3 class="anchored" data-anchor-id="question-3">Question 3</h3>
<p>How many trips were taken on the NYC Subway (Heavy Rail) in May 2024?</p>
<pre><code>USAGE |&gt;
  filter(
    month =="2004-05-01" &amp;
    mode == "Heavy Rail" &amp;
    agency == "MTA New York City Transit"
  ) |&gt;
  select(agency, mode, month, unlinked_passenge_trips)</code></pre>
</section>
<section id="output-4" class="level3">
<h3 class="anchored" data-anchor-id="output-4">output:</h3>
<table class="table-striped table-hover caption-top table">
<caption>Data for Trips Taken on NYC Subway in May 2024</caption>
<colgroup>
<col style="width: 36%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 32%">
</colgroup>
<thead>
<tr class="header">
<th>agency</th>
<th>mode</th>
<th>month</th>
<th>unlinked_passenger_trips</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>MTA New York City Transit</td>
<td>Heavy Rail</td>
<td>2004-05-01</td>
<td>184,334,430</td>
</tr>
</tbody>
</table>
</section>
<section id="answer-3" class="level3">
<h3 class="anchored" data-anchor-id="answer-3">Answer 3</h3>
<p><strong>184,334,430 trips</strong></p>
<p>If you divide this figure by 30 (days in a month), and then divide that result by 8,300,000 (population of NYC), the average New Yorker takes .7402 subway rides a day.</p>
<hr>
</section>
<section id="question-4" class="level3">
<h3 class="anchored" data-anchor-id="question-4"><del>Question 4</del></h3>
<p><del>What mode of transport had the longest average trip in May 2024?</del></p>
<hr>
</section>
<section id="question-5" class="level3">
<h3 class="anchored" data-anchor-id="question-5">Question 5</h3>
<p>How much did NYC subway ridership fall between April 2019 and April 2020?</p>
<pre><code> subway_ridership &lt;- USAGE |&gt;
  filter(
      agency == 'MTA New York City Transit' &amp;
      mode == "Heavy Rail" &amp;
      (month == "2019-05-01" | month == "2020-05-01")
      )

subway_ridership_2019 &lt;- subway_ridership[1,]$unlinked_passenge_trips
subway_ridership_2020 &lt;- subway_ridership[2,]$unlinked_passenge_trips

subway_ridership_2019 - subway_ridership_2020</code></pre>
<pre><code># [1] 210561702</code></pre>
</section>
<section id="answer-5" class="level3">
<h3 class="anchored" data-anchor-id="answer-5">Answer 5:</h3>
<p>184,334,430</p>
<p><strong>Note:</strong></p>
<p>Covid sucked.</p>
<hr>
</section>
<section id="three-four-more-interesting-transit-facts-in-this-data" class="level3">
<h3 class="anchored" data-anchor-id="three-four-more-interesting-transit-facts-in-this-data">Three (four) more interesting transit facts in this data</h3>
</section>
<section id="fact-1" class="level3">
<h3 class="anchored" data-anchor-id="fact-1">FACT 1</h3>
<p><img src="../images/incline.jpg" class="img-fluid" style="width:50%; box-shadow: -2px 3px 3px rgba(0, 0, 0, 0.5); display: block; margin: auto;"></p>
<p>In Pittsburgh, PA there is a unique form of uphill rail transit called the <a href="https://en.m.wikipedia.org/wiki/Duquesne_Incline">Duquesne Incline</a>. It offers arguably the most scenic view of Downtown Pittsburgh and the convergence of the city’s “Three Rivers.” Do tourists largely ride the Duquesne Incline? :</p>
<p><em>from Wikipedia:</em></p>
<blockquote class="blockquote">
<p>The incline was intended to carry cargo up and down Mt. Washington in the late 19th century. It later carried passengers, particularly Mt. Washington residents who were tired of walking up the steep footpaths to the top of the bluff. Inclines were being built all over Mt. Washington to serve working-class people who were forced out of the lowlying riverfront by industrial development</p>
</blockquote>
<p>I was interested to see if the ridership numbers suggested any traditional transit usage, or if the incline was now primarily used for “transit tourism”.</p>
<pre><code>month_map &lt;- c(
  "01" = "January",
  "02" = "February",
  "03" = "March",
  "04" = "April",
  "05" = "May",
  "06" = "June",
  "07" = "July",
  "08" = "August",
  "09" = "September",
  "10" = "October",
  "11" = "November",
  "12" = "December"
)

USAGE |&gt;
  filter(startsWith(agency, "Pitt")) |&gt;
  filter(mode == "Inclined Plane") |&gt;
  mutate(month_split = strsplit(as.character(month), "-")) |&gt;
  mutate(month_num = sapply(month_split, function(x) x[2])) |&gt;
  mutate(month_name = month_map[month_num]) |&gt;
  group_by(month_name) |&gt;
  summarize(total_this_month = sum(unlinked_passenge_trips)) |&gt;
  arrange(desc(total_this_month))</code></pre>
</section>
<section id="output-5" class="level3">
<h3 class="anchored" data-anchor-id="output-5">output:</h3>
<table class="table-striped table-hover caption-top table">
<caption>Data for Yearly Ridership of the Pittsburgh Inclined Plane</caption>
<thead>
<tr class="header">
<th>month_name</th>
<th>total_this_month</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>July</td>
<td>1,715,940</td>
</tr>
<tr class="even">
<td>August</td>
<td>1,507,425</td>
</tr>
<tr class="odd">
<td>June</td>
<td>1,424,861</td>
</tr>
<tr class="even">
<td>May</td>
<td>1,224,003</td>
</tr>
<tr class="odd">
<td>September</td>
<td>1,128,166</td>
</tr>
<tr class="even">
<td>October</td>
<td>1,061,274</td>
</tr>
<tr class="odd">
<td>April</td>
<td>1,032,881</td>
</tr>
<tr class="even">
<td>November</td>
<td>965,257</td>
</tr>
<tr class="odd">
<td>March</td>
<td>895,805</td>
</tr>
<tr class="even">
<td>December</td>
<td>877,248</td>
</tr>
<tr class="odd">
<td>January</td>
<td>666,924</td>
</tr>
<tr class="even">
<td>February</td>
<td>641,834</td>
</tr>
</tbody>
</table>
</section>
<section id="conclusion" class="level3">
<h3 class="anchored" data-anchor-id="conclusion">Conclusion</h3>
<p>The ridership numbers spiking in the summer, along with stark drop off in ridership from December to January, suggest the incline is largely popular with tourists and not used as much by the hill-weary residents of Mt. Washington.</p>
<hr>
</section>
<section id="fact-2" class="level3">
<h3 class="anchored" data-anchor-id="fact-2">FACT 2</h3>
<p><img src="../images/red-state-blue-state.jpg" class="img-fluid" style="width:50%; box-shadow: -2px 3px 3px rgba(0, 0, 0, 0.5); display: block; margin: auto;"></p>
<p>As our country remains polarized on so many issues and cultural concern, I was curious if there was an obvious Red vs.&nbsp;Blue divide over transit usage in this country.</p>
<p>I wanted to see if I could identify any obvious distinctions or division in the use of transit between Red States and Blue States.</p>
<pre><code>USAGE |&gt;
  #there is def some code smell here :
  mutate(state_split = strsplit(metro_area, ", ")) |&gt;
  mutate(state = sapply(state_split, function(st) st[2])) |&gt;
  mutate(state_split = strsplit(state, "-")) |&gt;
  mutate(state = sapply(state_split, function(st) st[1])) |&gt;
  group_by(state) |&gt;
  summarize(total_trips = sum(unlinked_passenge_trips)) |&gt;
  arrange(desc(total_trips)) |&gt;
  print(n = 20)</code></pre>
</section>
<section id="output-6" class="level3">
<h3 class="anchored" data-anchor-id="output-6">output:</h3>
<table class="table-striped table-hover caption-top table">
<caption>Data for Total State Transit Trips</caption>
<thead>
<tr class="header">
<th>state</th>
<th>total_trips</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>NY</td>
<td>85,530,025,008</td>
</tr>
<tr class="even">
<td>CA</td>
<td>27,099,834,336</td>
</tr>
<tr class="odd">
<td>IL</td>
<td>12,744,773,889</td>
</tr>
<tr class="even">
<td>DC</td>
<td>9,057,818,580</td>
</tr>
<tr class="odd">
<td>PA</td>
<td>8,776,976,555</td>
</tr>
<tr class="even">
<td>MA</td>
<td>7,993,427,892</td>
</tr>
<tr class="odd">
<td>FL</td>
<td>5,742,223,542</td>
</tr>
<tr class="even">
<td>TX</td>
<td>5,466,164,685</td>
</tr>
<tr class="odd">
<td>WA</td>
<td>4,524,992,934</td>
</tr>
<tr class="even">
<td>GA</td>
<td>3,096,203,662</td>
</tr>
<tr class="odd">
<td>OR</td>
<td>2,555,837,796</td>
</tr>
<tr class="even">
<td>OH</td>
<td>2,364,107,111</td>
</tr>
<tr class="odd">
<td>MD</td>
<td>2,271,510,025</td>
</tr>
<tr class="even">
<td>CO</td>
<td>2,144,454,426</td>
</tr>
<tr class="odd">
<td>MN</td>
<td>1,909,216,918</td>
</tr>
<tr class="even">
<td>MI</td>
<td>1,776,345,495</td>
</tr>
<tr class="odd">
<td>NV</td>
<td>1,395,503,197</td>
</tr>
<tr class="even">
<td>AZ</td>
<td>1,384,679,690</td>
</tr>
<tr class="odd">
<td>MO</td>
<td>1,371,031,013</td>
</tr>
<tr class="even">
<td>HI</td>
<td>1,225,521,578</td>
</tr>
</tbody>
</table>
</section>
<section id="conclusion-1" class="level3">
<h3 class="anchored" data-anchor-id="conclusion-1">Conclusion</h3>
<p>There does in fact look to be a Red vs.&nbsp;Blue divide over transit usage in this country. While this list is indeed dominated by many <strong>Blue States</strong>, I believe the most convincing evidence for this fact are state rankings #7 - #11.</p>
<p>Both Florida, Texas and Georgia - <em>all <strong>Red States</strong></em> - are among the largest states by population in the United States.</p>
<ol type="1">
<li>Florida Population: <strong>22.4 million</strong></li>
<li>Texas Population: <strong>30.03 million</strong></li>
<li>Georgia Population: <strong>10.9 million</strong></li>
</ol>
<p>However, Oregon and Washingon are neighbors to those 3 large Red states in this ranking of transit use.</p>
<p>Yet Oregon and Washington - <em>both <strong>Blue States</strong></em> - are medium-sized states in terms of population counts.</p>
<ol type="1">
<li>Washington Population <strong>7.786 million</strong></li>
<li>Oregon Population <strong>4.2 million</strong></li>
</ol>
<p>That Oregon and Washinton maintain comparable volumes of transit usage, despite significantly lower populations than large <strong>Red States</strong> like Florida, Texas and Georgia, suggest there is a Red v. Blue divide over transit usage in the United States.</p>
<p>A better exercise would be to measure transit trips / population to see the per capita number for ridership.</p>
<hr>
</section>
<section id="fact-3" class="level3">
<h3 class="anchored" data-anchor-id="fact-3">FACT 3</h3>
<p><img src="../images/si_ferry.jpg" class="img-fluid" style="width:50%; box-shadow: -2px 3px 3px rgba(0, 0, 0, 0.5); display: block; margin: auto;"></p>
<p>This is interesting :</p>
<pre><code>USAGE |&gt;
  group_by(agency) |&gt;
  summarize(total_trips = sum(unlinked_passenge_trips),
            total_miles = sum(vehicle_revenue_miles),
            num_ppl_mile = total_trips / total_miles
            ) |&gt;
  arrange(desc(total_trips)) |&gt;
  slice(1:50) |&gt;
  arrange(desc(average_trip)) |&gt;
  print(n = 50)</code></pre>
</section>
<section id="output-7" class="level3">
<h3 class="anchored" data-anchor-id="output-7">output:</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 48%">
<col style="width: 18%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>agency</th>
<th>total_trips</th>
<th>total_miles</th>
<th>num_ppl_mile</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>New York City Department of Transportation</td>
<td>440,538,576</td>
<td>4,150,573</td>
<td>106</td>
</tr>
<tr class="even">
<td>Washington State Ferries</td>
<td>502,394,973</td>
<td>20,230,767</td>
<td>24.8</td>
</tr>
<tr class="odd">
<td>City and County of San Francisco</td>
<td>4,533,445,698</td>
<td>583,200,690</td>
<td>7.77</td>
</tr>
</tbody>
</table>
</section>
<section id="conclusion-2" class="level3">
<h3 class="anchored" data-anchor-id="conclusion-2">Conclusion</h3>
<p>This looks to be communicating that Ferries are very efficient vehicles for transporting a lot of people over small distances. Every <a href="https://www.nyc.gov/html/dot/html/ferrybus/ferry-facts.shtml#:~:text=John%20J.,16%20knots%2C%20and%209%2C000%20horsepower.">SI Ferry carries around ~4,000 people !</a></p>
<hr>
</section>
<section id="fact-4" class="level3">
<h3 class="anchored" data-anchor-id="fact-4">FACT 4</h3>
<p><img src="../images/monorail_man.jpg" class="img-fluid" style="width:50%; box-shadow: -2px 3px 3px rgba(0, 0, 0, 0.5); display: block; margin: auto; margin-bottom: 10px;"> <img src="../images/monorail_map.jpg" class="img-fluid" style="width:50%; box-shadow: -2px 3px 3px rgba(0, 0, 0, 0.5); display: block; margin: auto;"></p>
<p>This charismatic, tune-carrying charlatan has swindled unknowing cities like Ogdenville, North Haverbrook and Brockway into buying dubious monorail systems for their communities.</p>
<p>I was interested to see where this snake-oil salesman - with a voice of gold! - has worked his sly sales magic across the United States…</p>
<pre><code>USAGE |&gt;
  filter(mode == "Guided Transit (Monorail)") |&gt;
  group_by(metro_area) |&gt;
  summarize(count = n())</code></pre>
</section>
<section id="output-8" class="level3">
<h3 class="anchored" data-anchor-id="output-8">output:</h3>
<table class="table-striped table-hover caption-top table">
<caption>Monorails Systems in the United States</caption>
<thead>
<tr class="header">
<th>metro_area</th>
<th>count</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Detroit, MI</td>
<td>151</td>
</tr>
<tr class="even">
<td>Jacksonville, FL</td>
<td>151</td>
</tr>
<tr class="odd">
<td>Las Vegas–Henderson–Paradise, NV</td>
<td>34</td>
</tr>
<tr class="even">
<td>Miami–Fort Lauderdale, FL</td>
<td>151</td>
</tr>
<tr class="odd">
<td>Morgantown, WV</td>
<td>145</td>
</tr>
<tr class="even">
<td>San Francisco–Oakland, CA</td>
<td>116</td>
</tr>
<tr class="odd">
<td>Seattle–Tacoma, WA</td>
<td>151</td>
</tr>
</tbody>
</table>
</section>
<section id="conclusion-3" class="level3">
<h3 class="anchored" data-anchor-id="conclusion-3">Conclusion</h3>
<p>Detroit, MI, Morgantown, WV and Jacksonville, FL are a few of the US cities where brain-dead slobs work cushy jobs on this very unique, very rare form of mass transit.</p>
<hr>
</section>
</section>
<section id="task-5-table-summarization" class="level1">
<h1>Task 5: Table Summarization</h1>
<p>Create a new table from USAGE that has annual total (sum) UPT and VRM for 2022. This will require use of the group_by, summarize, and filter functions. You will also want to use the year function, to extract a year from the month column.</p>
<pre><code>USAGE_2022_ANNUAL &lt;- USAGE |&gt;
  mutate(year = year(month)) |&gt;
  filter(year(month) == 2022) |&gt;
  group_by(year, metro_area, agency, mode, `NTD ID`) |&gt;
  summarize(total_upt = sum(unlinked_passenge_trips, na.rm = TRUE),
            total_vrm = sum(vehicle_revenue_miles, na.rm = TRUE)) |&gt;
  select(`NTD ID`, agency, metro_area, mode, total_upt, total_vrm, year) |&gt;
  filter(total_upt &gt; 400000) |&gt;
  ungroup()

USAGE_AND_FINANCIALS &lt;- left_join(USAGE_2022_ANNUAL,
                                  FINANCIALS,
                                  join_by(`NTD ID`, mode)) |&gt;
  rename(
    "total_fares" = "Total Fares",
    "expenses" = "Expenses",
  ) |&gt;
  select(-"Agency Name") |&gt;
  drop_na() |&gt;
  
print(USAGE_AND_FINANCIALS, n = 5)</code></pre>
<section id="output-9" class="level3">
<h3 class="anchored" data-anchor-id="output-9">output:</h3>
<table class="table-striped table-hover caption-top table">
<caption>Data for 2022 Usage and Financials</caption>
<colgroup>
<col style="width: 5%">
<col style="width: 31%">
<col style="width: 15%">
<col style="width: 12%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 3%">
<col style="width: 8%">
<col style="width: 7%">
</colgroup>
<thead>
<tr class="header">
<th>NTD ID</th>
<th>agency</th>
<th>metro_area</th>
<th>mode</th>
<th>total_upt</th>
<th>total_vrm</th>
<th>year</th>
<th>total_fares</th>
<th>expenses</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>50010</td>
<td>METRO Regional Transit Authority</td>
<td>Akron, OH</td>
<td>Motor Bus</td>
<td>3,470,765</td>
<td>3,252,489</td>
<td>2022</td>
<td>2,345,779</td>
<td>38,200,740</td>
</tr>
<tr class="even">
<td>50021</td>
<td>Portage Area Regional Transportation Authority</td>
<td>Akron, OH</td>
<td>Motor Bus</td>
<td>591,881</td>
<td>672,463</td>
<td>2022</td>
<td>1,933,660</td>
<td>6,197,595</td>
</tr>
<tr class="odd">
<td>20002</td>
<td>Capital District Transportation Authority</td>
<td>Albany–Schenectady, NY</td>
<td>Motor Bus</td>
<td>12,656,760</td>
<td>8,723,783</td>
<td>2022</td>
<td>7,947,384</td>
<td>95,586,715</td>
</tr>
<tr class="even">
<td>60019</td>
<td>City of Albuquerque</td>
<td>Albuquerque, NM</td>
<td>Bus Rapid Transit</td>
<td>1,829,848</td>
<td>792,000</td>
<td>2022</td>
<td>38,268</td>
<td>6,535,431</td>
</tr>
<tr class="odd">
<td>60019</td>
<td>City of Albuquerque</td>
<td>Albuquerque, NM</td>
<td>Motor Bus</td>
<td>4,151,408</td>
<td>3,788,377</td>
<td>2022</td>
<td>738,682</td>
<td>40,436,564</td>
</tr>
</tbody>
</table>
<hr>
</section>
</section>
<section id="task-6-farebox-recovery-among-major-systems" class="level1">
<h1>Task 6: Farebox Recovery Among Major Systems</h1>
<section id="question-1-1" class="level3">
<h3 class="anchored" data-anchor-id="question-1-1">Question 1</h3>
<p>Which transit system (agency and mode) had the most UPT in 2022?</p>
<pre><code>USAGE_AND_FINANCIALS |&gt;
  arrange(desc(total_upt)) |&gt;
  select(agency, mode, total_upt)</code></pre>
</section>
<section id="output-10" class="level3">
<h3 class="anchored" data-anchor-id="output-10">output:</h3>
<table class="table-striped table-hover caption-top table">
<caption>Transit GOATs</caption>
<colgroup>
<col style="width: 68%">
<col style="width: 14%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>agency</th>
<th>mode</th>
<th>total_upt</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>MTA New York City Transit</td>
<td>Heavy Rail</td>
<td>1,793,073,801</td>
</tr>
<tr class="even">
<td>MTA New York City Transit</td>
<td>Motor Bus</td>
<td>458,602,305</td>
</tr>
<tr class="odd">
<td>Los Angeles County Metropolitan Transportation Authority</td>
<td>Motor Bus</td>
<td>193,637,448</td>
</tr>
<tr class="even">
<td>Los Angeles County Metropolitan Transportation Authority</td>
<td>Motor Bus</td>
<td>193,637,448</td>
</tr>
<tr class="odd">
<td>Chicago Transit Authority</td>
<td>Motor Bus</td>
<td>140,013,945</td>
</tr>
</tbody>
</table>
</section>
<section id="answer-1-1" class="level3">
<h3 class="anchored" data-anchor-id="answer-1-1">Answer 1:</h3>
<p>MTA New York City Transit Heavy Rail: <strong>1,793,073,801</strong></p>
<p><strong>Note:</strong></p>
<p>While New York City’s inclusion on this list is understandable, along with Chicago: the 3rd largest city in the United States, seen as an historical pre-war, pre-automobile city… the inclusion of Los Angeles County is arguably surprising.</p>
<p>While LA County is of significant population size, it is considered a “sprawled out” metro area most friendly to the automobile. Despite this reputation, and despite the challenges of offering transit in a region with lower population density, LA county’s high transit ridership suggests the existence of an undeniable appetite for quality transit.</p>
<hr>
</section>
<section id="question-2-1" class="level3">
<h3 class="anchored" data-anchor-id="question-2-1">Question 2:</h3>
<p>Which transit system (agency and mode) had the highest farebox recovery, defined as the highest ratio of Total Fares to Expenses?</p>
<pre><code>USAGE_AND_FINANCIALS |&gt;
  mutate(farebox_recovery = total_fares / expenses ) |&gt;
  arrange(desc(farebox_recovery)) |&gt;
  select(agency, mode, farebox_recovery) |&gt;
  print(n = 5)</code></pre>
</section>
<section id="output-11" class="level3">
<h3 class="anchored" data-anchor-id="output-11">output:</h3>
<table class="table-striped table-hover caption-top table">
<caption>Private Ride You’re Going to Pay</caption>
<colgroup>
<col style="width: 61%">
<col style="width: 17%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>agency</th>
<th>mode</th>
<th>farebox_recovery</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Port Imperial Ferry Corporation</td>
<td>Ferry Boat</td>
<td>1.43</td>
</tr>
<tr class="even">
<td>Hyannis Harbor Tours, Inc.</td>
<td>Ferry Boat</td>
<td>1.41</td>
</tr>
<tr class="odd">
<td>Trans-Bridge Lines, Inc.</td>
<td>Commuter Bus</td>
<td>1.33</td>
</tr>
<tr class="even">
<td>Chattanooga Area Regional Transportation Authority</td>
<td>Inclined Plane</td>
<td>1.31</td>
</tr>
<tr class="odd">
<td>Regional Transportation Commission of Washoe County</td>
<td>Vanpool</td>
<td>1.24</td>
</tr>
</tbody>
</table>
</section>
<section id="answer-2-1" class="level3">
<h3 class="anchored" data-anchor-id="answer-2-1">Answer 2:</h3>
<p>Port Imperial Ferry Corporation, Ferry Boat: <strong>1.43</strong></p>
<p><strong>Note:</strong></p>
<p>Port Imperial Ferry, Haynnis Harbor Tours and Trans-Bridge Lines are all private companies. As private companies, their fares <strong>must</strong> exceed their expenses as their operations are not supported by any government entity. Furthermore, business owners expect profit on their capital investment and assumption of risk. This is consistent with an observation of fares outpacing revenue.</p>
<hr>
</section>
<section id="question-3-1" class="level3">
<h3 class="anchored" data-anchor-id="question-3-1">Question 3:</h3>
<p>Which transit system (agency and mode) has the lowest expenses per UPT?</p>
<pre><code>USAGE_AND_FINANCIALS |&gt;
  mutate(expenses_UPT = expenses / total_upt ) |&gt;
  arrange(expenses_UPT) |&gt;
  select(agency, mode, expenses_UPT)</code></pre>
</section>
<section id="output-12" class="level3">
<h3 class="anchored" data-anchor-id="output-12">output:</h3>
<table class="table-striped table-hover caption-top table">
<caption>Where is the NYU Shuttle?</caption>
<thead>
<tr class="header">
<th>agency</th>
<th>mode</th>
<th>expenses_UPT</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>North Carolina State University</td>
<td>Motor Bus</td>
<td>1.18</td>
</tr>
<tr class="even">
<td>Anaheim Transportation Network</td>
<td>Motor Bus</td>
<td>1.28</td>
</tr>
<tr class="odd">
<td>University of Iowa</td>
<td>Motor Bus</td>
<td>1.54</td>
</tr>
<tr class="even">
<td>Chatham Area Transit Authority</td>
<td>Ferry Boat</td>
<td>1.60</td>
</tr>
<tr class="odd">
<td>Texas State University</td>
<td>Motor Bus</td>
<td>2.05</td>
</tr>
</tbody>
</table>
</section>
<section id="answer-3-1" class="level3">
<h3 class="anchored" data-anchor-id="answer-3-1">Answer 3:</h3>
<p>North Carolina State University, Motor Bus : <strong>1.18 $/ride</strong></p>
<p><strong>Note:</strong></p>
<p>It’s logical that the transit systems with the lowest expense per ride serve universities. College campuses are communities with two factors suited for offering affordable, cost-sensitive transit: a high population density (students are mostly in dorms and shared housing) and a smaller surface for transit coverage (the routes are limited to a college campus, not an entire city).</p>
<hr>
</section>
<section id="question-4-1" class="level3">
<h3 class="anchored" data-anchor-id="question-4-1">Question 4:</h3>
<p>Which transit system (agency and mode) has the highest total fares per UPT?</p>
<pre><code>USAGE_AND_FINANCIALS |&gt;
  mutate(fares_UPT = total_fares / total_upt ) |&gt;
  arrange(desc(fares_UPT)) |&gt;
  select(agency, mode, fares_UPT)</code></pre>
</section>
<section id="output-13" class="level3">
<h3 class="anchored" data-anchor-id="output-13">output:</h3>
<table class="table-striped table-hover caption-top table">
<caption>Soak the Rich</caption>
<colgroup>
<col style="width: 63%">
<col style="width: 21%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th>agency</th>
<th>mode</th>
<th>fares_UPT</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Hampton Jitney, Inc.</td>
<td>Commuter Bus</td>
<td>41.3</td>
</tr>
<tr class="even">
<td>Pennsylvania Department of Transportation</td>
<td>Commuter Rail</td>
<td>32.3</td>
</tr>
<tr class="odd">
<td>Hyannis Harbor Tours, Inc.</td>
<td>Ferry Boat</td>
<td>29.6</td>
</tr>
<tr class="even">
<td>Trans-Bridge Lines, Inc.</td>
<td>Commuter Bus</td>
<td>28.1</td>
</tr>
<tr class="odd">
<td>SeaStreak, LLC</td>
<td>Ferry Boat</td>
<td>22.1</td>
</tr>
</tbody>
</table>
</section>
<section id="answer-4" class="level3">
<h3 class="anchored" data-anchor-id="answer-4">Answer 4</h3>
<p>Hampton Jitney: <strong>41.3 $/trip</strong></p>
<p><strong>Note:</strong></p>
<p>The Hampton Jitney is a logical candidate to collect the highest fares for every ride (i.e.&nbsp;its riders pay the most) because it is responsible for transporting some the wealthiest residents of New York City to some of the most desirable vacationing in the United States - the famed beach community “The Hamptons.” If you can charge wealthy customers more for a service they can afford, as a business person, why wouldn’t you? What’s more, the Hampton Jitney vehicles are outfitted with amenities to comfort the wealthy riders who use the service. Seemingly the higher fares are not only going to transportation expenses, but also on-bus goodies used to appeal to a luxury audience.</p>
<hr>
</section>
<section id="question-5-1" class="level3">
<h3 class="anchored" data-anchor-id="question-5-1">Question 5</h3>
<p>Which transit system (agency and mode) has the lowest expenses per VRM?</p>
<pre><code>USAGE_AND_FINANCIALS |&gt;
  mutate(expenses_VRM = expenses / total_vrm ) |&gt;
  arrange(expenses_VRM) |&gt;
  select(agency, mode, expenses_VRM)</code></pre>
</section>
<section id="output-14" class="level3">
<h3 class="anchored" data-anchor-id="output-14">output:</h3>
<table class="table-striped table-hover caption-top table">
<caption>Vanlyfe</caption>
<colgroup>
<col style="width: 71%">
<col style="width: 12%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>agency</th>
<th>mode</th>
<th>expenses_VRM</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Metropolitan Transportation Commission</td>
<td>Vanpool</td>
<td>0.445</td>
</tr>
<tr class="even">
<td>San Joaquin Council</td>
<td>Vanpool</td>
<td>0.498</td>
</tr>
<tr class="odd">
<td>San Diego Association of Governments</td>
<td>Vanpool</td>
<td>0.540</td>
</tr>
<tr class="even">
<td>Regional Transportation Commission of Washoe County</td>
<td>Vanpool</td>
<td>0.566</td>
</tr>
<tr class="odd">
<td>Los Angeles County Metropolitan Transportation Authority</td>
<td>Vanpool</td>
<td>0.581</td>
</tr>
</tbody>
</table>
</section>
<section id="answer-5-1" class="level3">
<h3 class="anchored" data-anchor-id="answer-5-1">Answer 5</h3>
<p>Metropolitan Transportation Commission : <strong>0.445 $/mile</strong></p>
<p><strong>Note:</strong></p>
<p>Vanpool’s efficiency stems from 1. it being easier to run a smaller van at capacity than a larger bus and 2. it being subsidized by non-road users. The highway trust fund has long been running a deficit as gas tax revenues have not kept up with <a href="https://frontiergroup.org/resources/who-pays-roads/">the cost of highway construction and maintenance</a>. Because vanpool can run its vehicles consistently at full capacity, and can use infrastructure that is not fully supported by road user fees, it suggests an efficient form of transit.</p>
<hr>
</section>
<section id="question" class="level3">
<h3 class="anchored" data-anchor-id="question">Question :</h3>
<p>Which transit system (agency and mode) has the highest total fares per VRM?</p>
<pre><code>USAGE_AND_FINANCIALS |&gt;
  mutate(fares_VRM = total_fares / total_vrm ) |&gt;
  arrange(desc(fares_VRM)) |&gt;
  select(agency, mode, fares_VRM)</code></pre>
</section>
<section id="output-15" class="level3">
<h3 class="anchored" data-anchor-id="output-15">output:</h3>
<table class="table-striped table-hover caption-top table">
<caption>Expensive Boats</caption>
<colgroup>
<col style="width: 70%">
<col style="width: 17%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th>agency</th>
<th>mode</th>
<th>fares_VRM</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Jacksonville Transportation Authority</td>
<td>Ferry Boat</td>
<td>158.0</td>
</tr>
<tr class="even">
<td>Chattanooga Area Regional Transportation Authority</td>
<td>Inclined Plane</td>
<td>149.0</td>
</tr>
<tr class="odd">
<td>Hyannis Harbor Tours, Inc.</td>
<td>Ferry Boat</td>
<td>138.0</td>
</tr>
<tr class="even">
<td>SeaStreak, LLC</td>
<td>Ferry Boat</td>
<td>115.0</td>
</tr>
<tr class="odd">
<td>Cape May Lewes Ferry</td>
<td>Ferry Boat</td>
<td>93.0</td>
</tr>
</tbody>
</table>
</section>
<section id="answer-6" class="level3">
<h3 class="anchored" data-anchor-id="answer-6">Answer 6</h3>
<p>Jacksonville Transportation Authority : <strong>158.0 $/mile</strong></p>
<p><strong>Note:</strong></p>
<p>Ferries are often necessary, not because a rider needs to travel long distances, but because a body of water is serving as an insurmountable transportation barrier.</p>
<p>Ferries are expensive. Here in NYC, ferries operate at <a href="https://www.6sqft.com/nyc-ferrys-gets-a-10-37-per-ride-subsidy-despite-fewer-annual-riders-than-the-subway-has-in-a-day/">10X the subsidy as a subway ride</a>. Presumably the higher fares collected by these transit agencies are needed to cover the ferry boat’s higher expenses. With the combination of a larger numerator (the ferry fares) and a smaller denominator (miles traveled) we can understand the results found here.</p>
<hr>
</section>
<section id="based-on-all-of-this-what-do-you-believe-to-be-the-most-efficient-transit-system-in-the-country-your-answer-may-differ-depending-on-which-form-of-efficiency-you-care-most-about" class="level3">
<h3 class="anchored" data-anchor-id="based-on-all-of-this-what-do-you-believe-to-be-the-most-efficient-transit-system-in-the-country-your-answer-may-differ-depending-on-which-form-of-efficiency-you-care-most-about">Based on all of this, what do you believe to be the most efficient transit system in the country? (Your answer may differ depending on which form of ‘efficiency’ you care most about)</h3>
<p>Transit use is an unmistakable social, ecological and economical good. It enhances opportunity, reduces pollution and generates wealth through efficient land use.</p>
<p>As such, I believe the transit agency and mode that provides the most trips is <em>the most efficient system</em>:</p>
</section>
</section>
<section id="mta-new-york-city-transit-heavy-rail-1793073801" class="level1">
<h1><strong>MTA New York City Transit, Heavy Rail: 1,793,073,801</strong></h1>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/jasonamey\.github\.io\/STA9750-2024-FALL\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>